### ISSUE TITLE
Crypto.randomBytes() is not a function

### ISSUE THREAD

**Issue by RevuraV** [S2-/securerandomstring#10]
I have some issue after update node version. 
secure-random-string package in the inside use the next line: `var crypto = require('crypto');`
as i see https://www.npmjs.com/package/crypto it's already deprecated and all things crypto (for example crypto.randomBytes) not working.
Uncaught TypeError: crypto.randomBytes is not a function, this what i see in the console
Would be this issue fixed?

**Comment by 5im-0n** [comment]
`secure-random-string` has no deps on an external package crypto.
