### ISSUE TITLE
"Generated string is too short. Please catch this Error and try again"

### ISSUE THREAD

**Issue by 70nyIT** [S2-/securerandomstring#11]
As per my title, I got this error when generating the string with the following setup

```typescript
const randomSuffix = srs({
    length: 15,
    alphanumeric: true,
  });
```

I've run the same code thousands of time and this is the first and only time that error happened. First of all, I'd like to understand why, and it's not clear to me how this could happen. Secondly, I think the package should handle it and retry itself. Any thoughts on this?

**Comment by 5im-0n** [comment]
fixed in v1.1.4

**Comment by 5im-0n** [comment]
This can happen if the system is short on entropy. The code was changed to try again, but if there is no entropy securerandomstring will crash when the call stack becomes to big.

**Comment by 70nyIT** [comment]
Thanks for the fast response @5im-0n ! To give more context (if this can help other users), this happened on as AWS Lambda function
