### ISSUE TITLE
suggestion: async code should callback with the error not throw it. 

### ISSUE THREAD

**Issue by markstos** [S2-/securerandomstring#2]
In async Node code, it's conventional to callback with the error as the first argument instead of throwing the error. 

This is also the behavior of the underlying `crypto.randomBytes` function that is being used. I recommend a breaking change for the async API to follow this Node.js convention of having the callback return a possible error as the first argument.

**Comment by S2-** [comment]
closed in 6d46d068ccbcaa

**Comment by 5im-0n** [comment]
hi mark, i gave you push rights on master of this repo. if you want to push a patch you are welcome.

**Comment by markstos** [comment]
Thanks for the commit access. I've created a pull request that addresses the docs/tests/code/changelog for this feature if you want to take a look. If approve, it's ready for a 1.0.0. 

I bumped the major version since the addition of the error to the callback is breaking change. 

https://github.com/S2-/securerandomstring/pull/3

**Comment by 5im-0n** [comment]
looks good. merged.
