### ISSUE TITLE
Use alphabetic chars only

### ISSUE THREAD

**Issue by sandrogomez** [S2-/securerandomstring#7]
Hello guys, I put some lines of code to allow create token with alphabetic chars only.

I'm thinking to add new features like only numbers .. etc.

Are you supporting this package yet?

Thanks in advance.
https://github.com/S2-/securerandomstring/pull/6

**Comment by 5im-0n** [comment]
hi @mrsangrin, sure the patch is cool! could you just add the paramater usage instructions to the readme and maybe add a test?

**Comment by 5im-0n** [comment]
@mrsangrin do you want me to release on npm or do you want to add some other stuff before publishing?

**Comment by sandrogomez** [comment]
@S2- Im working on your recommendation 
* Adding docs into Readme
* Adding Test to the new feature.

**Comment by 5im-0n** [comment]
@mrsangrin you should also add yourself to the contributors list!

**Comment by sandrogomez** [comment]
@S2- I put a new PR in order to improve
* Contributors List
* New feature option test

https://github.com/S2-/securerandomstring/pull/8/
